import { sql } from 'slonik';

import { connection } from 'modules/database';

export async function checkDatabaseConnection() {
  return connection.exists(sql<queries.One>`SELECT 1 as "one"`);
}

export declare namespace queries {
  // Generated by @slonik/typegen

  /** - query: `SELECT 1 as "one"` */
  export interface One {
    /** regtype: `integer` */
    one: number | null;
  }
}
